# Generated by Django 5.2.4 on 2026-06-16 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_texto', models.CharField(help_text='Username o correo ingresado', max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('resultado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('BLOQUEADO', 'Bloqueado')], default='FALLIDO', max_length=10)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro de acceso',
                'verbose_name_plural': 'Registros de acceso',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterField(
            model_name='empresasaas',
            name='nit',
            field=models.CharField(blank=True, default='', max_length=30, unique=True),
        ),
    ]
